package com.vomiter.extradelight.common.items;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

import com.mojang.datafixers.util.Pair;
import com.vomiter.extradelight.registry.ExtraDelightMobEffects;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import vectorwing.farmersdelight.common.FoodValues;
import vectorwing.farmersdelight.common.registry.ModEffects;

public class EDFoods {
    public static Map<FoodProperties, Supplier<Item>> CONVERT_MAP = new HashMap<>();

    public static class EDFoodPropertyBuilder{
        private final FoodProperties.Builder food;
        private Supplier<Item> convertTo = null;
        public EDFoodPropertyBuilder(){
            food = new FoodProperties .Builder();
        }

        public EDFoodPropertyBuilder usingConvertsTo(Item item){
            convertTo = () -> item;
            return this;
        }
        
        public EDFoodPropertyBuilder nutrition(int i) {
            food.nutrition(i);
            return this;
        }

        public EDFoodPropertyBuilder saturationMod(float s) {
            food.saturationMod(s);
            return this;
        }

        public EDFoodPropertyBuilder meat() {
            food.meat();
            return this;
        }

        public EDFoodPropertyBuilder alwaysEat() {
            food.alwaysEat();
            return this;
        }

        public EDFoodPropertyBuilder fast() {
            food.fast();
            return this;
        }

        public EDFoodPropertyBuilder effect(java.util.function.Supplier<MobEffectInstance> effectIn, float probability) {
            food.effect(effectIn, probability);
            return this;
        }
        
        public FoodProperties build(){
            var f = food.build();
            if(convertTo != Items.AIR){
                CONVERT_MAP.put(f, convertTo);
            }
            return f;
        }
    }
    
    public static final Supplier<MobEffectInstance> ROT = () -> new MobEffectInstance(MobEffects.CONFUSION,FoodValues.SHORT_DURATION,0);
    public static final Supplier<MobEffectInstance> ABSORPTION_SHORT = () -> new MobEffectInstance(MobEffects.ABSORPTION,FoodValues.SHORT_DURATION,0);
    public static final Supplier<MobEffectInstance> GOLDEN_APPLE_1 = () -> new MobEffectInstance(MobEffects.REGENERATION,100,1);
    public static final Supplier<MobEffectInstance> GOLDEN_APPLE_2 = () -> new MobEffectInstance(MobEffects.ABSORPTION,2400,0);
    public static final Supplier<MobEffectInstance> HUNGER = () -> new MobEffectInstance(MobEffects.HUNGER,600,0);
    public static final Supplier<MobEffectInstance> JUMP_BRIEF = () -> new MobEffectInstance(MobEffects.JUMP,FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> REGENERATION_BRIEF = () -> new MobEffectInstance(MobEffects.REGENERATION,FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> DAMAGE_RESISTANCE_MEDIUM = () -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE,FoodValues.MEDIUM_DURATION,0);
    public static final Supplier<MobEffectInstance> DOLPHIN_BRIEF = () -> new MobEffectInstance(MobEffects.DOLPHINS_GRACE,FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> COMFORT_BRIEF = () -> new MobEffectInstance(ModEffects.COMFORT.get(),FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> COMFORT_MEDIUM = () -> new MobEffectInstance(ModEffects.COMFORT.get(),FoodValues.MEDIUM_DURATION,0);
    public static final Supplier<MobEffectInstance> COMFORT_LONG = () -> new MobEffectInstance(ModEffects.COMFORT.get(),FoodValues.LONG_DURATION,0);
    public static final Supplier<MobEffectInstance> NOURISHMENT_BRIEF = () -> new MobEffectInstance(ModEffects.NOURISHMENT.get(),FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> NOURISHMENT_MEDIUM = () -> new MobEffectInstance(ModEffects.NOURISHMENT.get(),FoodValues.MEDIUM_DURATION,0);
    public static final Supplier<MobEffectInstance> NOURISHMENT_LONG = () -> new MobEffectInstance(ModEffects.NOURISHMENT.get(),FoodValues.LONG_DURATION,0);
    public static final Supplier<MobEffectInstance> GLOW_SHORT = () -> new MobEffectInstance(MobEffects.GLOWING,FoodValues.SHORT_DURATION,0);
    public static final Supplier<MobEffectInstance> PAIN = () -> new MobEffectInstance(MobEffects.HARM,1,0);
    public static final Supplier<MobEffectInstance> SPEED_BRIEF = () -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED,FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> FIRE_RESISTANCE_BRIEF = () -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE,FoodValues.BRIEF_DURATION,0);
    public static final Supplier<MobEffectInstance> FIRE_RESISTANCE_MEDIUM = () -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE,FoodValues.MEDIUM_DURATION,0);
    public static final Supplier<MobEffectInstance> SPEED_MEDIUM = () -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED,FoodValues.MEDIUM_DURATION,0);
    public static final Supplier<MobEffectInstance> FIRE_RESISTANCE_SHORT = () -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE,FoodValues.SHORT_DURATION,0);
    public static final Supplier<MobEffectInstance> FIRE_RESISTANCE_LONG = () -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE,FoodValues.LONG_DURATION,0);
    
	public static final Supplier<MobEffectInstance> PICKLED_ONE = () -> new MobEffectInstance(ExtraDelightMobEffects.PICKLED.get(),FoodValues.LONG_DURATION,0);
	public static final Supplier<MobEffectInstance> PICKLED_TWO = () -> new MobEffectInstance(ExtraDelightMobEffects.PICKLED.get(),FoodValues.LONG_DURATION,1);
	public static final Supplier<MobEffectInstance> PICKLED_THREE = () -> new MobEffectInstance(ExtraDelightMobEffects.PICKLED.get(),FoodValues.LONG_DURATION,2);
	public static final Supplier<MobEffectInstance> PICKLED_FOUR = () -> new MobEffectInstance(ExtraDelightMobEffects.PICKLED.get(),FoodValues.LONG_DURATION,3);
	public static final Supplier<MobEffectInstance> SOUR_PUCKER_ONE = () -> new MobEffectInstance(ExtraDelightMobEffects.SOUR_PUCKER.get(),FoodValues.BRIEF_DURATION,0);
	public static final Supplier<MobEffectInstance> SOUR_PUCKER_TWO = () -> new MobEffectInstance(ExtraDelightMobEffects.SOUR_PUCKER.get(),FoodValues.BRIEF_DURATION,1);
	public static final Supplier<MobEffectInstance> SOUR_PUCKER_THREE = () -> new MobEffectInstance(ExtraDelightMobEffects.SOUR_PUCKER.get(),FoodValues.BRIEF_DURATION,2);
	public static final Supplier<MobEffectInstance> SOUR_PUCKER_FOUR = () -> new MobEffectInstance(ExtraDelightMobEffects.SOUR_PUCKER.get(),FoodValues.BRIEF_DURATION,3);
	public static final Supplier<MobEffectInstance> SUNSHINE_ONE = () -> new MobEffectInstance(ExtraDelightMobEffects.SUNSHINE.get(),FoodValues.LONG_DURATION,0);
	public static final Supplier<MobEffectInstance> SUNSHINE_TWO = () -> new MobEffectInstance(ExtraDelightMobEffects.SUNSHINE.get(),FoodValues.LONG_DURATION,1);
	public static final Supplier<MobEffectInstance> SUNSHINE_THREE = () -> new MobEffectInstance(ExtraDelightMobEffects.SUNSHINE.get(),FoodValues.LONG_DURATION,2);
	public static final Supplier<MobEffectInstance> SUNSHINE_FOUR = () -> new MobEffectInstance(ExtraDelightMobEffects.SUNSHINE.get(),FoodValues.LONG_DURATION,3);


    public static final FoodProperties NOTFOOD = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0f).alwaysEat().build();
    public static final FoodProperties BADFOOD = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(ROT, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CUSTARD = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).usingConvertsTo(Items.GLASS_BOTTLE).alwaysEat().build();
    public static final FoodProperties WHIPPED_CREAM = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).usingConvertsTo(Items.BOWL).alwaysEat().build();
    public static final FoodProperties EDIBLE_SEEDS = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).alwaysEat().build();
    public static final FoodProperties SUGAR = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).alwaysEat().build();
    public static final FoodProperties OIL = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties VINEGAR = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties MILK = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).build();
    public static final FoodProperties MUSHROOM = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.3f).build();
    public static final FoodProperties FLOUR = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).build();
    public static final FoodProperties BAD_FOOD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.1f).effect(ROT, 0.8F).build();
    public static final FoodProperties CHEESE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).build();
    public static final FoodProperties BUTTER = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).build();
    public static final FoodProperties COOKED_SAUSAGE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_BRAIN = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_HEART = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_LIVER = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_LUNG = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_STOMACH = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).build();
    public static final FoodProperties COOKED_TRIPE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).build();
    public static final FoodProperties CACTUS = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).effect(PAIN, 1F).build();
    public static final FoodProperties COOKED_CORN = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties GRILLED_CORN = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).build();
    public static final FoodProperties ICE_CREAM = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).usingConvertsTo(Items.BOWL).alwaysEat().build();
    public static final FoodProperties TOPPED_ICE_CREAM = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).usingConvertsTo(Items.BOWL).alwaysEat().build();
    public static final FoodProperties COOKIE_DOUGH = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).build();
    public static final FoodProperties SLICED_ONION = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.4f).build();
    public static final FoodProperties SLICED_TOMATO = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.3f).build();
    public static final FoodProperties COOKED_CARROT = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).build();
    public static final FoodProperties COOKED_APPLE = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.3f).build();
    public static final FoodProperties SLICED_BREAD = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties BREADING = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).build();
    public static final FoodProperties MAYO = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties BBQ = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.4f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties KETCHUP = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.3f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties GRAVY = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.7f).effect(REGENERATION_BRIEF, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties JAM = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties SCRAMBLED_EGGS = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).build();
    public static final FoodProperties OMELETTE = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.8f).build();
    public static final FoodProperties QUICHE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).build();
    public static final FoodProperties EGG_BASKET = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).build();
    public static final FoodProperties EGG_SALAD = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FRIED_POTATO = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).build();
    public static final FoodProperties GLAZED_CARROT = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).build();
    public static final FoodProperties CARROT_SALAD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties APPLE_SAUCE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties POTATO_SOUP = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties TOMATO_SOUP = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FISH_SOUP = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CARROT_SOUP = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties SALISBURY_STEAK = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MASHED_POTATO_GRAVY = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).effect(REGENERATION_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PORK_STEW = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LAMB_STEW = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHICKEN_STEW = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CURRY = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BEEF_STEW_RICE = new EDFoodPropertyBuilder().nutrition(18).saturationMod(0.8f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PORK_STEW_RICE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.8f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LAMB_STEW_RICE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.8f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties RABBIT_STEW_RICE = new EDFoodPropertyBuilder().nutrition(16).saturationMod(0.6f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHICKEN_STEW_RICE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FISH_STEW_RICE = new EDFoodPropertyBuilder().nutrition(18).saturationMod(0.8f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CURRY_RICE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.7f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties COOKED_PASTA = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.3f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BUTTERED_PASTA = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FRIED_FISH = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.6f).build();
    public static final FoodProperties CHICKEN_FRIED_STEAK = new EDFoodPropertyBuilder().nutrition(17).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties PORK_TENDERLOIN = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties PORK_TENDERLOIN_SANDWICH = new EDFoodPropertyBuilder().nutrition(15).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties CHEESE_SANDWICH = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).build();
    public static final FoodProperties GRILLED_CHEESE = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.6f).build();
    public static final FoodProperties AGAR_AGAR_POWDER = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.3f).build();
    public static final FoodProperties HASH = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.8f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MEAT_LOAF = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MEAT_LOAF_SANDWICH = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_LONG, 1F).build();
    public static final FoodProperties MEAT_PIE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties PULLED_PORK_SERVING = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.8f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PULLED_PORK_SANDWICH = new EDFoodPropertyBuilder().nutrition(15).saturationMod(0.8f).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties STIRFRY = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties STIRFRY_RICE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.8f).effect(NOURISHMENT_MEDIUM, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties JELLY = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.3f).effect(JUMP_BRIEF, 0.5F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MACARONI_AND_CHEESE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LASAGNA = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties JERKY = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.8f).build();
    public static final FoodProperties SAUSAGE_ROLL = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.8f).build();
    public static final FoodProperties SOS = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.8f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LIVERONION = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.8f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FRIED_CHICKEN = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties STUFFED_HEART = new EDFoodPropertyBuilder().nutrition(16).saturationMod(0.8f).build();
    public static final FoodProperties FRIED_BRAIN = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.8f).build();
    public static final FoodProperties OXTAIL_SOUP = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties POT_ROAST = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BBQ_RIBS = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties RACK_LAMB = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties WELLINGTON = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties HAGGIS = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties HOTDISH = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FURIKAKE_RICE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.4f).effect(DOLPHIN_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FISH_CAKES = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.6f).build();
    public static final FoodProperties FISH_CHIPS = new EDFoodPropertyBuilder().nutrition(18).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties FRIED_MUSHROOMS = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).build();
    public static final FoodProperties MUSHROOM_RISOTTO = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties STUFFED_MUSHROOMS = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).build();
    public static final FoodProperties MUSHROOM_BURGER = new EDFoodPropertyBuilder().nutrition(15).saturationMod(0.8f).build();
    public static final FoodProperties BACON_EGG_SANDWICH = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.8f).build();
    public static final FoodProperties BACON_EGG_CHEESE_SANDWICH = new EDFoodPropertyBuilder().nutrition(16).saturationMod(0.8f).build();
    public static final FoodProperties BUTTERED_TOAST = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).build();
    public static final FoodProperties SALAD = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(NOURISHMENT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties ALFREDO_SAUCE = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PASTA_TOMATO = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PASTA_ALFREDO = new EDFoodPropertyBuilder().nutrition(14).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHICKEN_ALFREDO = new EDFoodPropertyBuilder().nutrition(20).saturationMod(0.6f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHICKEN_PARM = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties CHEESEBURGER = new EDFoodPropertyBuilder().nutrition(15).saturationMod(0.8f).effect(COMFORT_BRIEF, 1F).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties BACON_CHEESEBURGER = new EDFoodPropertyBuilder().nutrition(19).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties RICEBALL = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.4f).effect(DOLPHIN_BRIEF, 1F).build();
    public static final FoodProperties RICEBALL_FILLED = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.4f).effect(DOLPHIN_BRIEF, 1F).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties FISH_SALAD = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FISH_SALAD_SANDWICH = new EDFoodPropertyBuilder().nutrition(17).saturationMod(0.6f).build();
    public static final FoodProperties SEAWEED_CRISPS = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).effect(DOLPHIN_BRIEF, 1F).build();
    public static final FoodProperties SEAWEED_SALAD = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).effect(DOLPHIN_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties COOKED_CACTUS = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.3f).build();
    public static final FoodProperties CACTUS_EGGS = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.4f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CACTUS_SOUP = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CACTUS_SALAD = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.6f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties STUFFED_CACTUS = new EDFoodPropertyBuilder().nutrition(17).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties CORN_CHOWDER = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CREAMED_CORN = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CORN_FRITTERS = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties STEWED_APPLES = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties APPLE_FRITTERS = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.4f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CARAMEL_SAUCE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties CARAMEL_CANDY = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CANDY = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CANDY_APPLE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CARAMEL_APPLE = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CANDY_GOLDEN_APPLE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(1.2f).effect(GOLDEN_APPLE_1, 1F).effect(GOLDEN_APPLE_2, 1F).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CARAMEL_GOLDEN_APPLE = new EDFoodPropertyBuilder().nutrition(8).saturationMod(1.2f).effect(GOLDEN_APPLE_1, 1F).effect(GOLDEN_APPLE_2, 1F).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CARAMEL_POPCORN = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CORNBREAD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties APPLE_CRISP = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties STUFFING = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.7f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CORN_PUDDING = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties POTATOES_AU_GRATIN = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FROSTING = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.6f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties CANDY_CANE = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties FRENCH_TOAST = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CONGEE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.4f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LUGAW = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.7f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MUFFIN = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties FILLED_BREAD = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.6f).build();
    public static final FoodProperties PICKLED_GINGER = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).effect(PICKLED_ONE, 1F).alwaysEat().build();
    public static final FoodProperties BEET_MINT = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CRACKER = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.6f).alwaysEat().build();
    public static final FoodProperties CROQUE_MONSIEUR = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.8f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CROQUE_MADAME = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties ROLL = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties CINNAMON_ROLL = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties MONKEY_BREAD = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MINT_LAMB = new EDFoodPropertyBuilder().nutrition(15).saturationMod(0.8f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHARCUTERIE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).alwaysEat().build();
    public static final FoodProperties CHRISTMAS_PUDDING = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MILK_TART = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties CHOCOLATE_BAR = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.1f).effect(ABSORPTION_SHORT, 1F).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties CHOCOLATE_TRUFFLE = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).effect(ABSORPTION_SHORT, 1F).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties FILLED_CHOCOLATE_BAR = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.1f).effect(ABSORPTION_SHORT, 1F).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties CHOCOLATE_CHIPS = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.1f).effect(ABSORPTION_SHORT, 1F).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties MARSHMALLOW = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.4f).build();
    public static final FoodProperties CHILI = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(FIRE_RESISTANCE_BRIEF, 1F).build();
    public static final FoodProperties TOFFEE = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties GRAHAM_CRACKER = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).build();
    public static final FoodProperties SMORE = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.4f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties PEPPERMINT_BARK = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties DIRT_CAKE = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(SPEED_BRIEF, 1F).build();
    public static final FoodProperties TRAIL_MIX = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties NOUGAT = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).build();
    public static final FoodProperties GUMMIES = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.3f).effect(SPEED_BRIEF, 1F).build();
    public static final FoodProperties PEANUT_BRITTLE = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties BUTTERSCOTCH = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).build();
    public static final FoodProperties FLUFFER_NUTTER = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).build();
    public static final FoodProperties COFFEE_BEANS = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(SPEED_BRIEF, 1F).build();
    public static final FoodProperties ROASTED_COFFEE_BEANS = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.1f).effect(SPEED_MEDIUM, 1F).build();
    public static final FoodProperties BROWNIE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties BLONDIE = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties FUDGE = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties STICKY_TOFFEE_PUDDING = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties CEREAL = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.4f).effect(REGENERATION_BRIEF, 1F).effect(ABSORPTION_SHORT, 1F).build();
    public static final FoodProperties PUFFED_RICE_TREAT = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties SCOTCHAROO = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties BLACK_FOREST_TRIFLE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.1f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties DIPPED_SWEET_BERRY = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(COMFORT_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties DIPPED_GLOW_BERRY = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(COMFORT_BRIEF, 1F).effect(GLOW_SHORT, 1F).alwaysEat().build();
    public static final FoodProperties DIPPED_APPLE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).effect(COMFORT_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties DIPPED_MARSHMALLOW = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties DIPPED_GRAHAM_CRACKER = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties DIPPED_BACON = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).effect(COMFORT_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties NUTS = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).build();
    public static final FoodProperties PBJ = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties ICE_CREAM_SUNDAE = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties HAZELNUT_SPREAD = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties ROASTED_NUTS = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.1f).build();
    public static final FoodProperties DIPPED_COFFEE_BEAN = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).effect(COMFORT_BRIEF, 1F).effect(SPEED_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties ROMBOSSE = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties APPLE_SLAW = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PORK_AND_APPLES = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.4f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties APPLE_CHIPS = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.3f).build();
    public static final FoodProperties STUFFED_APPLE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties STUFFED_APPLE_ICE_CREAM = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.6f).effect(COMFORT_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MULLIGATAWNY_SOUP = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties TARTE_TATIN_SLICE = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties AEBLEFLAESK = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.4f).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties CANDY_BAR_SALAD = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.3f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MARSHMALLOW_FLUFF = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties NUT_BUTTER = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties JALAPENO_STUFFED_POTATO = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).effect(FIRE_RESISTANCE_MEDIUM, 1F).build();
    public static final FoodProperties JALAPENO_POPPER = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).effect(FIRE_RESISTANCE_SHORT, 1F).build();
    public static final FoodProperties CHILI_CHEESE_CORNBREAD_MUFFIN = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(FIRE_RESISTANCE_SHORT, 1F).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties CHILI_CON_CARNE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.7f).effect(NOURISHMENT_MEDIUM, 1F).effect(FIRE_RESISTANCE_LONG, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties WHITE_CHILI = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.7f).effect(NOURISHMENT_LONG, 1F).effect(FIRE_RESISTANCE_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MISSISSIPPI_MUD_PIE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties HAZELNUT_SOUP = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).effect(NOURISHMENT_MEDIUM, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties GRASSHOPPER_PIE = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties MARSHMALLOW_SLICE = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties ROCKY_ROAD = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).build();
    public static final FoodProperties AFFOGATO = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.6f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties POTATO_SALAD = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FRENCH_ONION_SOUP = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.7f).effect(NOURISHMENT_MEDIUM, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BACON_EGG_PIE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).effect(NOURISHMENT_MEDIUM, 1F).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties ONION_BHAJI = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).build();
    public static final FoodProperties FAT_POTATO = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CINNAMON_TOAST = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties PANFORTE = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.3f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties CURRYWURST = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).build();
    public static final FoodProperties BORSCHT = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PAMONHA = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties GARLIC = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.3f).build();
    public static final FoodProperties GARLIC_BREAD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).build();
    public static final FoodProperties CHEESY_GARLIC_BREAD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).build();
    public static final FoodProperties ROASTED_GARLIC = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).build();
    public static final FoodProperties AIOLI = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties CHICKEN_KIEV = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).build();
    public static final FoodProperties BRUSCETTA = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties DEVILLED_SAUSAGES = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties AGLIO_E_OLIO = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PENNE_ALL_ARRABBIATA = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CUCUMBER = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).build();
    public static final FoodProperties SOYBEANS = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.1f).build();
    public static final FoodProperties GHERKINS = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.3f).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties PICKLED_BEET = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties PICKLED_ONION = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.4f).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties PICKLED_CARROT = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.6f).effect(PICKLED_ONE, 1F).build();
    public static final FoodProperties PICKLED_EGG = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).effect(PICKLED_TWO, 1F).build();
    public static final FoodProperties PICKLED_FISH = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.1f).effect(PICKLED_TWO, 1F).build();
    public static final FoodProperties PICKLED_SAUSAGE = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.8f).effect(PICKLED_TWO, 1F).build();
    public static final FoodProperties SOY_SAUCE = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.3f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties SAUERKRAUT = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).effect(PICKLED_ONE, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties KIMCHI = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(PICKLED_TWO, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties HOT_SAUCE = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.6f).effect(FIRE_RESISTANCE_SHORT, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties MISO_PASTE = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.4f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties NATTO = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.1f).effect(ROT, 0.01F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties FISH_SAUCE = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.1f).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties SALAMI_MIX = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.3f).effect(HUNGER, 0.75F).build();
    public static final FoodProperties UNRIPE_SALAMI = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.3f).effect(HUNGER, 0.75F).build();
    public static final FoodProperties SALAMI = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties COOKED_SOYBEANS = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.1f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties NAEM_MOO = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.8f).effect(PICKLED_FOUR, 1F).build();
    public static final FoodProperties GAZPACHO = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties EDAMAME = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.1f).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BEEF_BULGOGI = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties HONEY_CHILI_CHICKEN = new EDFoodPropertyBuilder().nutrition(10).saturationMod(0.6f).effect(NOURISHMENT_LONG, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CARAMEL_CHICKEN = new EDFoodPropertyBuilder().nutrition(7).saturationMod(0.4f).effect(NOURISHMENT_LONG, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties SOY_GLAZED_SALMON = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties STEAK_PICKLED_ONION_PIE_SLICE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.8f).effect(COMFORT_LONG, 1F).effect(NOURISHMENT_MEDIUM, 1F).build();
    public static final FoodProperties KIWIBURGER = new EDFoodPropertyBuilder().nutrition(16).saturationMod(0.8f).effect(REGENERATION_BRIEF, 1F).effect(COMFORT_LONG, 1F).build();
    public static final FoodProperties SHIRAZI_SALAD = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.4f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CUCUMBER_SALAD = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.3f).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MISO_SOUP = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.7f).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties NATTO_AND_RICE = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.4f).effect(ROT, 0.01F).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties SAUERKRAUT_SOUP = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.7f).effect(PICKLED_THREE, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties SAUERKRAUT_AND_SAUSAGE = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.8f).effect(PICKLED_THREE, 1F).effect(COMFORT_BRIEF, 1F).effect(NOURISHMENT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties YEAST_SPREAD = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).effect(HUNGER, 0.05F).effect(REGENERATION_BRIEF, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties CHEESYMITE_SCROLL_SERVING = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(REGENERATION_BRIEF, 1F).effect(COMFORT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MORKOVCHA = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(NOURISHMENT_MEDIUM, 1F).effect(PICKLED_ONE, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties ZUPA_OGORKOWA = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.7f).effect(PICKLED_FOUR, 1F).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties KIMCHI_FRIED_RICE = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.6f).effect(PICKLED_THREE, 1F).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties KONGJANG = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.3f).effect(DAMAGE_RESISTANCE_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHEESEBURGER_PICKLE = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.8f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 1F).effect(PICKLED_TWO, 1F).build();
    public static final FoodProperties HOT_WINGS = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(FIRE_RESISTANCE_MEDIUM, 1F).effect(COMFORT_MEDIUM, 0F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties COOKED_WHEAT_SEEDS = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).build();
    public static final FoodProperties POPCORN = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.6f).build();
    public static final FoodProperties LEMON = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.2f).effect(SOUR_PUCKER_THREE, 1F).build();
    public static final FoodProperties LIME = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.2f).effect(SOUR_PUCKER_FOUR, 1F).build();
    public static final FoodProperties ORANGE = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.3f).effect(SOUR_PUCKER_TWO, 0.5F).build();
    public static final FoodProperties GRAPEFRUIT = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.3f).effect(SOUR_PUCKER_ONE, 0.5F).build();
    public static final FoodProperties ICE_CUBE = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0f).effect(FIRE_RESISTANCE_BRIEF, 1F).alwaysEat().build();
    public static final FoodProperties MELON_RIND = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.2f).build();
    public static final FoodProperties MERINGUE = new EDFoodPropertyBuilder().nutrition(0).saturationMod(0.4f).build();
    public static final FoodProperties LEMON_CURD = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.6f).effect(SUNSHINE_ONE, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties LEMON_MERINGUE_PIE_SLICE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(SUNSHINE_TWO, 1F).effect(COMFORT_BRIEF, 0F).build();
    public static final FoodProperties KEY_LIME_PIE_SLICE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).effect(SUNSHINE_TWO, 1F).effect(COMFORT_BRIEF, 0F).build();
    public static final FoodProperties MELON_GAZPACHO = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties THAI_MELON_SALAD = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.4f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties GRAPEFRUIT_BEET_SALAD = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.6f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CITRUS_ONION_SALAD = new EDFoodPropertyBuilder().nutrition(5).saturationMod(0.4f).effect(NOURISHMENT_MEDIUM, 1F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties BAKED_COD = new EDFoodPropertyBuilder().nutrition(6).saturationMod(0.3f).effect(NOURISHMENT_MEDIUM, 1F).effect(COMFORT_BRIEF, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties GRAPEFRUIT_SORBET = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.3f).effect(COMFORT_MEDIUM, 1F).effect(SUNSHINE_TWO, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHOCOLATE_ORANGE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.1f).effect(COMFORT_BRIEF, 1F).effect(SUNSHINE_ONE, 0F).build();
    public static final FoodProperties CHOCOLATE_MOUSSE = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties JAFFA_CAKE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).build();
    public static final FoodProperties GRILLED_GRAPEFRUIT = new EDFoodPropertyBuilder().nutrition(4).saturationMod(0.3f).effect(SUNSHINE_TWO, 1F).build();
    public static final FoodProperties LEMON_DELICIOUS = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.6f).effect(SUNSHINE_TWO, 1F).effect(SOUR_PUCKER_ONE, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties ORANGE_CHICKEN = new EDFoodPropertyBuilder().nutrition(12).saturationMod(0.6f).effect(SUNSHINE_TWO, 1F).effect(NOURISHMENT_MEDIUM, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties MELON_RIND_STIRFRY = new EDFoodPropertyBuilder().nutrition(14).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(NOURISHMENT_MEDIUM, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties LIME_SOUFFLE = new EDFoodPropertyBuilder().nutrition(9).saturationMod(0.6f).effect(SUNSHINE_THREE, 1F).effect(COMFORT_MEDIUM, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CHEESE_SOUFFLE = new EDFoodPropertyBuilder().nutrition(13).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).effect(ABSORPTION_SHORT, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties PAVLOVA_SLICE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.4f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties PRESERVED_LEMON = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.2f).effect(SUNSHINE_THREE, 1F).build();
    public static final FoodProperties PICKLED_MELON_RIND = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0f).build();
    public static final FoodProperties LEMON_PASTA = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.6f).effect(SUNSHINE_FOUR, 1F).effect(NOURISHMENT_MEDIUM, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties CANDIED_CITRUS_ZEST = new EDFoodPropertyBuilder().nutrition(1).saturationMod(0.2f).effect(SUNSHINE_ONE, 1F).build();
    public static final FoodProperties LEMON_POSSET = new EDFoodPropertyBuilder().nutrition(2).saturationMod(0.2f).effect(SUNSHINE_THREE, 1F).effect(SOUR_PUCKER_ONE, 0F).usingConvertsTo(Items.GLASS_BOTTLE).build();
    public static final FoodProperties MELON_LIME_CHICKEN = new EDFoodPropertyBuilder().nutrition(11).saturationMod(0.3f).effect(SUNSHINE_THREE, 1F).effect(NOURISHMENT_MEDIUM, 0F).usingConvertsTo(Items.BOWL).build();
    public static final FoodProperties KYIV_CAKE_SLICE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_BRIEF, 1F).build();
    public static final FoodProperties BAKED_ALASKA_SLICE = new EDFoodPropertyBuilder().nutrition(3).saturationMod(0.6f).effect(COMFORT_MEDIUM, 1F).build();
    public static final FoodProperties MELON_FRUIT_SALAD = new EDFoodPropertyBuilder().nutrition(8).saturationMod(0.6f).effect(REGENERATION_BRIEF, 1F).usingConvertsTo(Items.BOWL).build();
}